services:
  fastapi:
    build:
      context: .
      dockerfile: ./compose/run/Dockerfile
    command: uvicorn src.main:app --reload --host 0.0.0.0
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
volumes:
  pg_data: