services:
  test:
    build:
      context: .
      dockerfile: ./compose/test/Dockerfile
    env_file:
      - ./compose/test/.env.test
    volumes:
      - ./src:/app/src
    command: pytest tests/

  db:
    image: postgres
    env_file:
      - ./compose/test/.env.test