services:
  test:
    build:
      context: .
      dockerfile: ./compose/test/Dockerfile
    env_file:
      - ./compose/test/.env.test
    command: pytest tests/ -ss
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - ./compose/test/.env.test