"""add foreign key field

Revision ID: de00f7a37714
Revises: 04728138da6b
Create Date: 2023-12-20 19:12:41.955227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de00f7a37714'
down_revision: Union[str, None] = '04728138da6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_by_uuid', sa.Uuid(), nullable=False))
    op.create_foreign_key(op.f('fk_posts_created_by_uuid_users'), 'posts', 'users', ['created_by_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_posts_created_by_uuid_users'), 'posts', type_='foreignkey')
    op.drop_column('posts', 'created_by_uuid')
    # ### end Alembic commands ###
