name: APITest

on:
  push:
    branches: ["main"]

jobs:
  starlette:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
  
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy . 

      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .
      
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff
        run: ruff .
